/* Copyright 2026 Stanford University, NVIDIA Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __LEGION_INTERNAL_OPERATION_H__
#define __LEGION_INTERNAL_OPERATION_H__

#include "legion/operations/operation.h"

namespace Legion {
  namespace Internal {

    /**
     * \class InternalOp
     * The InternalOp class is an abstract intermediate class
     * for detecting when an operation is generated by the
     * runtime and not one created by the runtime. This
     * distinction is primarily emplyed by the tracing
     * infrastructure which can memoize analysis overheads
     * for application operations, but must still handle
     * internal operations correctly.
     */
    class InternalOp : public Operation {
    public:
      InternalOp(void);
      virtual ~InternalOp(void);
    public:
      void initialize_internal(Operation* creator, int creator_req_idx);
      virtual void activate(void) override;
      virtual void deactivate(bool free = true) override;
    public:
      virtual bool is_internal_op(void) const override { return true; }
      virtual const FieldMask& get_internal_mask(void) const = 0;
    public:
      inline Operation* get_creator_op(void) const { return create_op; }
      inline GenerationID get_creator_gen(void) const { return create_gen; }
      inline int get_internal_index(void) const { return creator_req_idx; }
      void record_trace_dependence(
          Operation* target, GenerationID target_gen, int target_idx,
          int source_idx, DependenceType dtype,
          const FieldMask& dependent_mask);
      virtual unsigned find_parent_index(unsigned idx) override;
    protected:
      // These things are really only needed for tracing
      // Information about the operation that generated
      // this close operation so we don't register dependences on it
      Operation* create_op;
      GenerationID create_gen;
      // The source index of the region requirement from the original
      // operation that generated this internal operation
      int creator_req_idx;
    };

  }  // namespace Internal
}  // namespace Legion

#endif  // __LEGION_INTERNAL_OPERATION_H__
