# Build Image for Gitlab CI

FROM ubuntu:24.04

MAINTAINER Elliott Slaughter <slaughter@cs.stanford.edu>

ENV DEBIAN_FRONTEND noninteractive

RUN dpkg --add-architecture i386 && \
    apt-get update -qq && \
    apt-get install -qq apt-transport-https ca-certificates software-properties-common wget && \
    add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
    apt-get update -qq && \
    apt-get install -qq \
      build-essential autoconf pkg-config gfortran git time wget curl ccache \
      libpython3-dev python3-pip pypy3 \
      python3-cffi python3-numpy python3-notebook python3-mypy \
      g++-10 g++-11 g++-12 \
      gfortran-10 gfortran-11 gfortran-12 \
      gcc-multilib g++-multilib \
      clang-18 clang-format-18 clang-tidy-18 lld-18 libclang-18-dev llvm-18-dev libomp-18-dev libmlir-18-dev libpolly-18-dev \
      libedit-dev libncurses5-dev libffi-dev libpfm4-dev libxml2-dev libzstd-dev \
      zlib1g-dev zlib1g-dev:i386 \
      mpich libmpich-dev \
      mesa-common-dev \
      libblas-dev liblapack-dev libhdf5-dev \
      libssl-dev \
      libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libfontconfig-dev \
      gdb vim && \
    apt-get clean

# Note: clang-format is NOT COMPATIBLE, even between POINT releases. (Ouch!!)
# Vendor the specific version we need here; THIS MUST NOT CHANGE without
# consulting the person who requires this version to be installed.
RUN wget https://github.com/terralang/llvm-build/releases/download/llvm-19.1.7/clang+llvm-19.1.7-x86_64-linux-gnu.tar.xz && \
    echo "1782684925971d8969b951ed941847b3871779346bd4df3b1ff92eed9dfa1319  clang+llvm-19.1.7-x86_64-linux-gnu.tar.xz" | shasum --check && \
    tar xf clang+llvm-19.1.7-x86_64-linux-gnu.tar.xz clang+llvm-19.1.7-x86_64-linux-gnu/bin/clang-format && \
    mv clang+llvm-19.1.7-x86_64-linux-gnu/bin/clang-format /usr/local/bin/clang-format-19 && \
    rm -rf clang+llvm-19.1.7-x86_64-linux-gnu*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain 1.85.1 -y

RUN wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-x86_64.tar.gz && \
    echo "ba1e0dcc710e2f92be6263f9617510b3660fa9dc409ad2fb8190299563f952a0  cmake-3.26.4-linux-x86_64.tar.gz" | shasum --check && \
    tar xfzC cmake-3.26.4-linux-x86_64.tar.gz /usr/local --strip-components=1 && \
    rm cmake-3.26.4-linux-x86_64.tar.gz

RUN git clone https://github.com/terralang/terra.git && \
    mkdir terra/deps && \
    cd terra/deps && \
    wget https://github.com/terralang/llvm-build/releases/download/llvm-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu.tar.xz && \
    echo "d9a1a9355fc6b07900200ae21af50c360c56bf56e163adcc253b7c041eb090a3  clang+llvm-18.1.8-x86_64-linux-gnu.tar.xz" | shasum --check && \
    tar xf clang+llvm-18.1.8-x86_64-linux-gnu.tar.xz && \
    cd ../.. && \
    cd terra/build && \
    cmake -DCMAKE_POLICY_DEFAULT_CMP0074=NEW -DLLVM_ROOT=$PWD/../deps/clang+llvm-18.1.8-x86_64-linux-gnu -DCMAKE_INSTALL_PREFIX=/usr/local/terra18 .. && \
    make install -j8 && \
    cd ../.. && \
    rm -rf terra

RUN pip3 install --break-system-packages 'pre-commit>=4.1,<5'

RUN wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.5.tar.gz && \
    echo "5cbefa0780b84f4126743c40cdd6a334b2f0574cd7fd95050fb1ac0ddbb7f0b8  openmpi-5.0.5.tar.gz" | shasum --check && \
    tar -xf openmpi-5.0.5.tar.gz && \
    mkdir -p openmpi-5.0.5/build /usr/local/ompi && \
    (cd openmpi-5.0.5/build && \
    ../configure --prefix=/usr/local/ompi --enable-mpirun-prefix-by-default && \
    make -j install) && \
    rm -rf openmpi-5.0.5.tar.gz openmpi-5.0.5
