# Build Image for Gitlab CI

FROM ubuntu:24.04

MAINTAINER Elliott Slaughter <slaughter@cs.stanford.edu>

ENV DEBIAN_FRONTEND noninteractive

RUN dpkg --add-architecture i386 && \
    apt-get update -qq && \
    apt-get install -qq apt-transport-https ca-certificates software-properties-common wget && \
    add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
    apt-get update -qq && \
    apt-get install -qq \
      build-essential pkg-config gfortran git time wget curl ccache \
      libpython3-dev python3-pip pypy3 \
      python3-cffi python3-numpy python3-notebook python3-mypy \
      g++-10 g++-11 g++-12 \
      gfortran-10 gfortran-11 gfortran-12 \
      gcc-multilib g++-multilib \
      clang-18 clang-format-18 clang-tidy-18 libclang-18-dev llvm-18-dev libomp-18-dev libmlir-18-dev \
      libedit-dev libncurses5-dev libffi-dev libpfm4-dev libxml2-dev \
      zlib1g-dev zlib1g-dev:i386 \
      mpich libmpich-dev \
      mesa-common-dev \
      libblas-dev liblapack-dev libhdf5-dev \
      libssl-dev \
      libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libfontconfig-dev \
      gdb vim && \
    apt-get clean

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain 1.84.0 -y

RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-x86_64.tar.gz && \
    echo "09e1b34026c406c5bf4d1b053eadb3a8519cb360e37547ebf4b70ab766d94fbc  cmake-3.22.6-linux-x86_64.tar.gz" | shasum --check && \
    tar xfzC cmake-3.22.6-linux-x86_64.tar.gz /usr/local --strip-components=1 && \
    rm cmake-3.22.6-linux-x86_64.tar.gz

RUN git clone https://github.com/terralang/terra.git && \
    cd terra/build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local/terra18 .. && \
    make install -j8 && \
    rm -rf terra
