variables:
  OLCF_SERVICE_ACCOUNT: ums036_auser
  GIT_SUBMODULE_STRATEGY: recursive

.rocm624: &rocm624
  ROCM_VERSION: "6.2.4"

.rocm631: &rocm631
  ROCM_VERSION: "6.3.1"

.rocm642: &rocm642
  ROCM_VERSION: "6.4.2"

.rocm702: &rocm702
  ROCM_VERSION: "7.0.2"

.rocm711: &rocm711
  ROCM_VERSION: "7.1.1"

.rocm720: &rocm720
  ROCM_VERSION: "7.2.0"

.legion: &legion
  TEST_REGENT: "0"
  LEGION_WARNINGS_FATAL: "1"
  DEBUG: "0"

.regent: &regent
  TEST_LEGION_CXX: "0"
  TEST_REALM: "0"
  TEST_FUZZER: "0"
  NO_PRETTY: "1"
  CXXFLAGS: "-D__HIP_PLATFORM_AMD__"

.cmake: &cmake
  USE_CMAKE: "1"

.ctest: &ctest
  TEST_CTEST: "1"

.nodes1: &nodes1
  SCHEDULER_PARAMETERS: "-A UMS036 -t 1:00:00 -N 1 -n 1 -c 56 -p batch --exclusive"

.nodes2: &nodes2
  SCHEDULER_PARAMETERS: "-A UMS036 -t 1:00:00 -N 2 -n 2 -c 56 -p batch --exclusive"

.tokens: &tokens
  id_tokens:
    OLCF_ID_TOKEN:
      aud: https://code.olcf.ornl.gov

.tests: &tests
  script:
    - .gitlab/prep_script.sh
    - .gitlab/test_script.sh
  retry:
    max: 0
    when:
      - runner_system_failure
      - unknown_failure

stages:
  - test

legion_cmake_rocm624:
  <<: [*tokens, *tests]
  stage: test
  tags:
    - slurm
    - frontier
    - login12
  variables:
    <<: [*legion, *cmake, *ctest, *rocm624, *nodes1]

legion_cmake_rocm631:
  <<: [*tokens, *tests]
  stage: test
  tags:
    - slurm
    - frontier
    - login12
  variables:
    <<: [*legion, *cmake, *ctest, *rocm631, *nodes1]

legion_cmake_rocm642:
  <<: [*tokens, *tests]
  stage: test
  tags:
    - slurm
    - frontier
    - login12
  variables:
    <<: [*legion, *cmake, *ctest, *rocm642, *nodes2]

legion_cmake_rocm702:
  <<: [*tokens, *tests]
  stage: test
  tags:
    - slurm
    - frontier
    - login12
  variables:
    <<: [*legion, *cmake, *ctest, *rocm702, *nodes1]

legion_cmake_rocm711:
  <<: [*tokens, *tests]
  stage: test
  tags:
    - slurm
    - frontier
    - login12
  variables:
    <<: [*legion, *cmake, *ctest, *rocm711, *nodes1]

legion_cmake_rocm720:
  <<: [*tokens, *tests]
  stage: test
  tags:
    - slurm
    - frontier
    - login12
  variables:
    <<: [*legion, *cmake, *ctest, *rocm720, *nodes1]

regent_cmake_rocm720:
  <<: [*tokens, *tests]
  stage: test
  tags:
    - slurm
    - frontier
    - login12
  variables:
    <<: [*regent, *cmake, *rocm720, *nodes2]
